apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: m7kvnmo6t-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/rhtap-qe:000839954572b749440c9675d91108e55758c2ff@sha256:2be86d4dec1e07aef0848bf02ad7a3ddeca22d1daa7a3594bd066750a6a84a49
          name: container-image
